/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type L1 = string;
export type L2 = string;
export type SearchAlgorithms = 'weighted_levenstein' | 'liblevenstein_automata';
export type Insertioncost = number;
export type Deletioncost = number;
export type Insertionatbeginningcost = number;
export type Deletionatendcost = number;
export type Substitutioncostspath = string | null;
export type Defaultsubstitutioncost = number;
export type StemmerEnum = 'snowball_english' | 'none';
export type Lower = boolean;
export type NormalizationEnum = 'NFC' | 'NFD' | 'NFKC' | 'NKFD' | 'none';
export type RemovePunctuation = string;
export type RemoveCombiningCharacters = boolean;
export type ReplaceRules = {
  [k: string]: string;
} | null;
export type Alphabet = string[];
export type OptionalFieldName = string;
export type Credits = Contributor[] | null;
export type Role = string;
export type Name = string;
export type Aboutpageimg = string | null;
export type Aboutpagedescription = string | null;
export type Build = string;
export type Word = string;
export type Definition = string;
export type Entryid = string;
export type SortingForm = number[];
export type Theme = string | null;
export type SecondaryTheme = string | null;
export type Img = string | null;
export type Audio = Audio1[] | null;
export type Description = string | null;
export type Filename = string;
export type Video = Video1[] | null;
export type Description1 = string | null;
export type Filename1 = string;
export type DefinitionAudio = Audio1[] | null;
export type ExampleSentence = string[] | null;
export type ExampleSentenceDefinition = string[] | null;
export type ExampleSentenceAudio = Audio1[][] | null;
export type ExampleSentenceDefinitionAudio = Audio1[][] | null;
export type Optional = {
  [k: string]: string;
} | null;
export type Source = string | null;
export type Data = DictionaryEntryExportFormat[];
/**
 * @minItems 2
 * @maxItems 2
 */
export type Location1 = [Entryindex, Positionindex];
export type Entryindex = string;
export type Positionindex = number;
export type Location = Location1[];

export interface MTDExportFormat {
  config: LanguageConfigurationExportFormat;
  data: Data;
  l1_index: L1Index;
  l2_index: L2Index;
}
export interface LanguageConfigurationExportFormat {
  L1: L1;
  L2: L2;
  l1_search_strategy: SearchAlgorithms;
  l2_search_strategy: SearchAlgorithms;
  l1_search_config?: WeightedLevensteinConfig | null;
  l2_search_config?: WeightedLevensteinConfig | null;
  l1_stemmer: StemmerEnum;
  l2_stemmer: StemmerEnum;
  l1_normalization_transducer: RestrictedTransducer;
  l2_normalization_transducer: RestrictedTransducer;
  alphabet: Alphabet;
  optional_field_name: OptionalFieldName;
  credits?: Credits;
  aboutPageImg?: Aboutpageimg;
  aboutPageDescription?: Aboutpagedescription;
  build: Build;
  [k: string]: unknown;
}
export interface WeightedLevensteinConfig {
  insertionCost?: Insertioncost;
  deletionCost?: Deletioncost;
  insertionAtBeginningCost?: Insertionatbeginningcost;
  deletionAtEndCost?: Deletionatendcost;
  substitutionCosts?: Substitutioncosts;
  substitutionCostsPath?: Substitutioncostspath;
  defaultSubstitutionCost?: Defaultsubstitutioncost;
}
export interface Substitutioncosts {
  [k: string]: {
    [k: string]: number;
  };
}
export interface RestrictedTransducer {
  lower?: Lower;
  unicode_normalization?: NormalizationEnum & string;
  remove_punctuation?: RemovePunctuation;
  remove_combining_characters?: RemoveCombiningCharacters;
  replace_rules?: ReplaceRules;
}
export interface Contributor {
  role: Role;
  name: Name;
}
/**
 * There is a DictionaryEntry created for each entry in your dictionary.
 * It intentionally shares the same data structure as the ParserTargets,
 * but allows for extra fields. This is the same as DictionaryEntry except with
 * some specifications for the output format (for example every exported entry will have)
 * a value for entryID, and a sorting_form).
 */
export interface DictionaryEntryExportFormat {
  word: Word;
  definition: Definition;
  entryID: Entryid;
  sorting_form: SortingForm;
  theme?: Theme;
  secondary_theme?: SecondaryTheme;
  img?: Img;
  audio?: Audio;
  video?: Video;
  definition_audio?: DefinitionAudio;
  example_sentence?: ExampleSentence;
  example_sentence_definition?: ExampleSentenceDefinition;
  example_sentence_audio?: ExampleSentenceAudio;
  example_sentence_definition_audio?: ExampleSentenceDefinitionAudio;
  optional?: Optional;
  source?: Source;
  [k: string]: unknown;
}
export interface Audio1 {
  description?: Description;
  filename: Filename;
  [k: string]: unknown;
}
export interface Video1 {
  description?: Description1;
  filename: Filename1;
  [k: string]: unknown;
}
export interface L1Index {
  [k: string]: {
    [k: string]: PostingData;
  };
}
export interface PostingData {
  location: Location;
  score: Score;
  [k: string]: unknown;
}
export interface Score {
  [k: string]: number;
}
export interface L2Index {
  [k: string]: {
    [k: string]: PostingData;
  };
}
