# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: '22'
      - name: Install
        run: |
          # The default config is for the monorepo, while this is for standalone
          npm install
      - name: Test
        run: |
          npx nx test search
      - name: Build
        run: |
          npx nx build search
          npx nx build mtd-mobile-ui --base-href=/mothertongues-UI/pr-preview/pr-${{github.event.number}}/ --configuration=production
          cp dist/packages/mtd-mobile-ui/index.html dist/packages/mtd-mobile-ui/404.html
      - name: Publish Deploy Preview 🛫
        uses: rossjrw/pr-preview-action@8ff09e486b4c23709012eedd3b42e9f0b95dd0c5 # v1.6.3
        with:
          source-dir: dist/packages/mtd-mobile-ui
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
