name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: |
          # The default config is for the monorepo, while this is for standalone
          npm install
      - name: Test
        run: |
          npx nx test search
      - name: Build
        run: |
          npx nx build search
          npx nx run mtd-mobile-ui:pre-build
          npx nx build mtd-mobile-ui --base-href=/mtd/ --configuration=production
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/packages/mtd-mobile-ui # The folder the action should deploy.
          force: false # rebase instead of force push by default
          clean-exclude: pr-preview/ # don't delete pr previews
